name: Quality

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Format check
        run: npm run format:check

      - name: Lint JS
        run: npm run lint:js

      - name: Lint CSS
        run: npm run lint:css

      - name: Build site
        run: npm run build

      - name: Build API docs
        run: npm run docs:api

      - name: Build site export
        run: npm run export

      - name: Lint HTML
        run: npm run lint:html

  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Build API docs
        run: npm run docs:api

      - name: Build site export
        run: npm run export

      - name: Run pa11y
        run: npm run a11y
